# Generated by Django 5.0.6 on 2025-04-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesPrediction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesante',
            name='blood_glucose_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneesante',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donneesante',
            name='hba1c_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneesante',
            name='heart_disease',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneesante',
            name='hypertension',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneesante',
            name='smoking_history',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('ever', 'Ever')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
