# Generated by Django 5.0.6 on 2025-04-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesPrediction', '0002_donneesante_blood_glucose_level_donneesante_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneesante',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='blood_glucose_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='bmi',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='hba1c_level',
            field=models.FloatField(default=5.5),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='heart_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='hypertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donneesante',
            name='smoking_history',
            field=models.CharField(choices=[('never', 'Never'), ('ever', 'Ever')], default='never', max_length=10),
        ),
    ]
