# Generated by Django 5.0.6 on 2025-04-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesPrediction', '0006_utilisateur_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='user',
        ),
    ]
