# Generated by Django 5.0.6 on 2025-04-30 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesPrediction', '0007_remove_utilisateur_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('calories', models.FloatField(help_text='Calories pour 100g')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(help_text='Quantité en grammes')),
                ('date', models.DateField(auto_now_add=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetesPrediction.aliment')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetesPrediction.utilisateur')),
            ],
        ),
    ]
