# Generated by Django 5.0.6 on 2025-05-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesPrediction', '0008_aliment_consommation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (little to no physical activity)'), ('moderate', 'Moderately Active (moderate exercise or physical activity)'), ('active', 'Active (intense exercise or physical activity)')], default='sedentary', max_length=10),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='male', max_length=6),
        ),
    ]
