# Generated by Django 5.0.6 on 2025-05-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesPrediction', '0009_utilisateur_activity_level_utilisateur_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='age',
            field=models.IntegerField(default=30),
        ),
    ]
