# Generated by Django 5.0.6 on 2025-05-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesPrediction', '0010_utilisateur_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
    ]
